# Generated by Django 4.2.3 on 2023-08-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=1, max_length=30, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
